name: Scheduled Job

on:
  workflow_dispatch:
  schedule:
    - cron: "45 6 * * *" #This runs every day at 5:50 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "This runs on a schedule"
