name: First Workflow #workflow name

on: 
  workflow_dispatch: #manual trigger
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest #runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: echo "Don't play games" 
